packages:
  - "packages/*"
saveExact: true
minimumReleaseAge: 4320 # 3 days
blockExoticSubdeps: false
allowBuilds:
  '@parcel/watcher': true
  bufferutil: true
  core-js-bundle: true
  core-js-pure: true
  ejs: true
  esbuild: true
  fsevents: true
  husky: true
  nx: true
  utf-8-validate: true
