/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["Wizards for 104 Address Element edit basic 104 Address looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[protocol104.wizard.title.addressEdit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      disabled=""
      label="IED"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DOI"
      readonly=""
      rows="2"
      type="textarea"
      value="AP1 / LD0 / LLN0 / Beh"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      disabled=""
      label="cdc"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DAI"
      readonly=""
      rows="2"
      type="textarea"
      value="stVal"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      helper="[protocol104.wizard.casduHelper]"
      label="casdu"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.ioaHelper]"
      label="ioa"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="ti"
      readonly=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="edit"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for 104 Address Element edit basic 104 Address looks like the latest snapshot */

snapshots["Wizards for 104 Address Element edit 104 Address with expected value looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[protocol104.wizard.title.addressEdit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      disabled=""
      label="IED"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DOI"
      readonly=""
      rows="2"
      type="textarea"
      value="AP1 / LD0 / GGIO-1 / Mod"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      disabled=""
      label="cdc"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DAI"
      readonly=""
      rows="2"
      type="textarea"
      value="Oper / ctlVal"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      helper="[protocol104.wizard.casduHelper]"
      label="casdu"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.ioaHelper]"
      label="ioa"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="ti"
      readonly=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="expectedValue"
      readonly=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="enumValue"
      readonly=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="edit"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for 104 Address Element edit 104 Address with expected value looks like the latest snapshot */

snapshots["Wizards for 104 Address Element edit 104 Address with unit multiplier looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[protocol104.wizard.title.addressEdit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      disabled=""
      label="IED"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DOI"
      readonly=""
      rows="2"
      type="textarea"
      value="AP1 / LD0 / GGIO-1 / IntIn1"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      disabled=""
      label="cdc"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DAI"
      readonly=""
      rows="2"
      type="textarea"
      value="stVal"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      helper="[protocol104.wizard.casduHelper]"
      label="casdu"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.ioaHelper]"
      label="ioa"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="ti"
      readonly=""
    >
    </wizard-textfield>
    <wizard-select
      fixedmenuposition=""
      helper="[protocol104.wizard.unitMultiplierHelper]"
      label="unitMultiplier"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="m"
      >
        <span>
          m
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="k"
      >
        <span>
          k
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="M"
      >
        <span>
          M
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="mu"
      >
        <span>
          mu
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="y"
      >
        <span>
          y
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="z"
      >
        <span>
          z
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="a"
      >
        <span>
          a
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="f"
      >
        <span>
          f
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="p"
      >
        <span>
          p
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="n"
      >
        <span>
          n
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="c"
      >
        <span>
          c
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="d"
      >
        <span>
          d
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="da"
      >
        <span>
          da
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="h"
      >
        <span>
          h
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="G"
      >
        <span>
          G
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="T"
      >
        <span>
          T
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="P"
      >
        <span>
          P
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="E"
      >
        <span>
          E
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="Z"
      >
        <span>
          Z
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="Y"
      >
        <span>
          Y
        </span>
      </mwc-list-item>
    </wizard-select>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="edit"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for 104 Address Element edit 104 Address with unit multiplier looks like the latest snapshot */

snapshots["Wizards for 104 Address Element edit 104 Address with scale fields looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[protocol104.wizard.title.addressEdit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      disabled=""
      label="IED"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DOI"
      readonly=""
      rows="2"
      type="textarea"
      value="AP1 / LD0 / MMXU-1 / Hz"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      disabled=""
      label="cdc"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DAI"
      readonly=""
      rows="2"
      type="textarea"
      value="mag / f"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      helper="[protocol104.wizard.casduHelper]"
      label="casdu"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.ioaHelper]"
      label="ioa"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="ti"
      readonly=""
    >
    </wizard-textfield>
    <wizard-select
      fixedmenuposition=""
      helper="[protocol104.wizard.unitMultiplierHelper]"
      label="unitMultiplier"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="m"
      >
        <span>
          m
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="k"
      >
        <span>
          k
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="M"
      >
        <span>
          M
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="mu"
      >
        <span>
          mu
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="y"
      >
        <span>
          y
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="z"
      >
        <span>
          z
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="a"
      >
        <span>
          a
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="f"
      >
        <span>
          f
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="p"
      >
        <span>
          p
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="n"
      >
        <span>
          n
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="c"
      >
        <span>
          c
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="d"
      >
        <span>
          d
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="da"
      >
        <span>
          da
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="h"
      >
        <span>
          h
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="G"
      >
        <span>
          G
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="T"
      >
        <span>
          T
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="P"
      >
        <span>
          P
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="E"
      >
        <span>
          E
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="Z"
      >
        <span>
          Z
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        value="Y"
      >
        <span>
          Y
        </span>
      </mwc-list-item>
    </wizard-select>
    <wizard-textfield
      helper="[protocol104.wizard.scaleMultiplierHelper]"
      label="scaleMultiplier"
      nullable=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.scaleOffsetHelper]"
      label="scaleOffset"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="edit"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for 104 Address Element edit 104 Address with scale fields looks like the latest snapshot */

snapshots["Wizards for 104 Address Element edit 104 Address with inverted value looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[protocol104.wizard.title.addressEdit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      disabled=""
      label="IED"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DOI"
      readonly=""
      rows="2"
      type="textarea"
      value="AP1 / LD0 / GGIO-1 / Ind2"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      disabled=""
      label="cdc"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DAI"
      readonly=""
      rows="2"
      type="textarea"
      value="stVal"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      helper="[protocol104.wizard.casduHelper]"
      label="casdu"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.ioaHelper]"
      label="ioa"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="ti"
      readonly=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="inverted"
      readonly=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="edit"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for 104 Address Element edit 104 Address with inverted value looks like the latest snapshot */

snapshots["Wizards for 104 Address Element edit 104 Address with check value looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[protocol104.wizard.title.addressEdit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      disabled=""
      label="IED"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DOI"
      readonly=""
      rows="2"
      type="textarea"
      value="AP1 / LD0 / GGIO-1 / DPCSO1"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      disabled=""
      label="cdc"
      readonly=""
    >
    </wizard-textfield>
    <oscd-filled-text-field
      autocomplete=""
      cols="40"
      disabled=""
      inputmode=""
      label="DAI"
      readonly=""
      rows="2"
      type="textarea"
      value="Oper / Check"
    >
    </oscd-filled-text-field>
    <wizard-textfield
      helper="[protocol104.wizard.casduHelper]"
      label="casdu"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[protocol104.wizard.ioaHelper]"
      label="ioa"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="ti"
      readonly=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="check"
      readonly=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="edit"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for 104 Address Element edit 104 Address with check value looks like the latest snapshot */

