import { PluginConfig } from './plugin.js';

export function generatePluginPath(plugin: string): string {
  return location.origin+location.pathname+plugin;
}

export const officialPlugins: PluginConfig[] = [
  {
    name: 'IED',
    src: '/oscd-plugins/editors/IED.js',
    icon: 'developer_board',
    activeByDefault: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Substation',
    src: '/oscd-plugins/editors/Substation.js',
    icon: 'margin',
    activeByDefault: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Single Line Diagram',
    src: '/oscd-plugins/editors/SingleLineDiagram.js',
    icon: 'edit',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Message Binding (GOOSE)',
    src: '/oscd-plugins/editors/GooseSubscriberMessageBinding.js',
    icon: 'link',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Data Binding (GOOSE)',
    src: '/oscd-plugins/editors/GooseSubscriberDataBinding.js',
    icon: 'link',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Message Binding (SMV)',
    src: '/oscd-plugins/editors/SMVSubscriberMessageBinding.js',
    icon: 'link',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Data Binding (SMV)',
    src: '/oscd-plugins/editors/SMVSubscriberDataBinding.js',
    icon: 'link',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Later Binding (SMV/GOOSE)',
    src: generatePluginPath('external-plugins/oscd-subscriber-later-binding/oscd-subscriber-later-binding.js'),
    icon: 'link',
    activeByDefault: true,
    kind: 'editor',
    requireDoc: true
  },
  {
    name: 'Communication',
    src: '/oscd-plugins/editors/Communication.js',
    icon: 'settings_ethernet',
    activeByDefault: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: '104',
    src: '/oscd-plugins/editors/Protocol104.js',
    icon: 'settings_ethernet',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Templates',
    src: '/oscd-plugins/editors/Templates.js',
    icon: 'copy_all',
    activeByDefault: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Publisher',
    src: generatePluginPath('external-plugins/oscd-publisher/oscd-publisher.js'),
    icon: 'publish',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Cleanup',
    src: '/oscd-plugins/editors/Cleanup.js',
    icon: 'cleaning_services',
    activeByDefault: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Open project',
    src: '/oscd-plugins/menu/OpenProject.js',
    icon: 'folder_open',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: false,
    position: 'top',
  },
  {
    name: 'New project',
    src: '/oscd-plugins/menu/NewProject.js',
    icon: 'create_new_folder',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: false,
    position: 'top',
  },
  {
    name: 'Plugin Store (Beta)',
    src: 'https://sprinteins.github.io/oscd-plugin-store/index.js',
    icon: 'shopping_bag',
    activeByDefault: false,
    kind: 'menu',
    requireDoc: false,
    position: 'bottom',
  },
  {
    name: 'Save project',
    src: '/oscd-plugins/menu/SaveProject.js',
    icon: 'save',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'top',
  },
  {
    name: 'Validate Schema',
    src: '/oscd-plugins/validators/ValidateSchema.js',
    icon: 'rule_folder',
    activeByDefault: true,
    kind: 'validator',
  },
  {
    name: 'Validate Templates',
    src: '/oscd-plugins/validators/ValidateTemplates.js',
    icon: 'rule_folder',
    activeByDefault: true,
    kind: 'validator',
  },
  {
    name: 'Import IEDs',
    src: '/oscd-plugins/menu/ImportIEDs.js',
    icon: 'snippet_folder',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Create Virtual IED',
    src: '/oscd-plugins/menu/VirtualTemplateIED.js',
    icon: 'developer_board',
    activeByDefault: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Subscriber Update',
    src: '/oscd-plugins/menu/SubscriberInfo.js',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Update desc (ABB)',
    src: '/oscd-plugins/menu/UpdateDescriptionABB.js',
    activeByDefault: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Update desc (SEL)',
    src: '/oscd-plugins/menu/UpdateDescriptionSEL.js',
    activeByDefault: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Merge Project',
    src: '/oscd-plugins/menu/Merge.js',
    icon: 'merge_type',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Update Substation',
    src: '/oscd-plugins/menu/UpdateSubstation.js',
    icon: 'merge_type',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Compare IED',
    src: '/oscd-plugins/menu/CompareIED.js',
    icon: 'compare_arrows',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Show SCL History',
    src: '/oscd-plugins/menu/SclHistory.js',
    icon: 'history_toggle_off',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: true,
    position: 'bottom',
  },
  {
    name: 'Help',
    src: '/oscd-plugins/menu/Help.js',
    icon: 'help',
    activeByDefault: true,
    kind: 'menu',
    requireDoc: false,
    position: 'bottom',
  },
  {
    name: 'Export Communication Section',
    src: '/oscd-plugins/menu/ExportCommunication.js',
    icon: 'sim_card_download',
    activeByDefault: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
];
